"""
Django settings for jumpnow project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import json
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dpq%t4mihe)zsl@si=)pzw*1jp3*@6ph-n7#)nvf)-b^apm3ah'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'accounts.apps.AccountsConfig',
    'discovery',
    'dashboard',
    'extras',
    'chat',
    'engage',
    'payments',
    'main',

    'channels',
    'widget_tweaks',
    'post_office',
    'django_instagram',
    'taggit',
    'django_filters',
    'hitcount',
    'simple_history',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'oauth2_provider',
    'mathfilters',
    'notifications',
    "algoliasearch_django",
    'import_export',
    'social_django',
    # "sslserver",
    'django_hosts',
]

SITE_ID = 1

MIDDLEWARE = [
#    'django_hosts.middleware.HostsRequestMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'simple_history.middleware.HistoryRequestMiddleware',
    'accounts.middlewares.OneSessionPerUser',
    'social_django.middleware.SocialAuthExceptionMiddleware',

#    'django_hosts.middleware.HostsResponseMiddleware',

]

INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'jumpnow.urls'

SOCIAL_AUTH_JSONFIELD_ENABLED = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context.gtag',
                'accounts.context.notifications',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'social_core.backends.instagram.InstagramOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',

]

WSGI_APPLICATION = 'jumpnow.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ASGI_APPLICATION = "jumpnow.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGIN_URL = '/admin/login/'
# LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard_new'
# LOGOUT_URL = 'logout'
# LOGOUT_REDIRECT_URL = 'login'
LOGOUT_REDIRECT_URL = '/admin/login/'

CSRF_TRUSTED_ORIGINS = ['app.jumpnow.agency', 'localhost:8000']

ALGOLIA = {
    'APPLICATION_ID': 'GL6G6ED5LB',
    'API_KEY': '855222f0731983f887a1951797e65ff1'
}

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email'

}
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('name', 'name'),
    ('email', 'email'),

]

SOCIAL_AUTH_TWITTER_KEY = 'I3lTAnvemwC6NaZK6lAIJ8qSz'
SOCIAL_AUTH_TWITTER_SECRET = 'N1fs1mezHL7BK8KlQuwoo4IZU83YwrFET2OlIASKLoWcMgq94O'

SOCIAL_AUTH_FACEBOOK_KEY = '322976155841255'
SOCIAL_AUTH_FACEBOOK_SECRET = '064d66c4012099716f97f6d8dce18d77'

SOCIAL_AUTH_INSTAGRAM_KEY = "1588114548193548"
SOCIAL_AUTH_INSTAGRAM_SECRET = "cde67329238c85605d1ef9330b26c8f3"
SOCIAL_AUTH_INSTAGRAM_SCOPE = ['user_profile', 'user_media']

DEFAULT_FROM_EMAIL = 'nikhileshcherukuri2@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'nikhileshcherukuri2@gmail.com'
EMAIL_HOST_PASSWORD = 'nikki8509@'

#ROOT_HOSTCONF = 'jumpnow.hosts'

#DEFAULT_HOST = ' '
