# Generated by Django 3.1.7 on 2021-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0002_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='open_for_bidding',
            field=models.BooleanField(default=True),
        ),
    ]
