# Generated by Django 3.1.7 on 2021-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_gig_open_for_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
