# Generated by Django 3.1.7 on 2021-06-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0004_gig_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectOfferPaymentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='directoffer',
            name='paid_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engage.directofferpaymentid'),
        ),
    ]
