# Generated by Django 3.1.7 on 2021-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0006_auto_20210628_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCreationCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_extra', models.IntegerField(default=0)),
                ('direct_offer_extra', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='directofferpaymentid',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gigpaymentid',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
