# Generated by Django 3.1.7 on 2021-06-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0008_auto_20210628_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='final_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
