# Generated by Django 3.1.7 on 2021-05-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('message', models.TextField()),
                ('message_type', models.CharField(max_length=50, null=True)),
                ('image_caption', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
