# Generated by Django 3.1.7 on 2021-05-30 17:52

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210530_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='image_caption',
            new_name='file_caption',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.message_file_path),
        ),
    ]
