# Generated by Django 3.1.7 on 2021-06-02 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210603_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
