# Generated by Django 3.1.7 on 2021-11-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_delete_acceptedcampaign'),
        ('dashboard', '0002_acceptedcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedcampaign',
            name='user',
        ),
        migrations.AddField(
            model_name='acceptedcampaign',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
