# Generated by Django 3.1.7 on 2021-11-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211126_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedcampaign',
            old_name='campaign',
            new_name='assigned_campaign',
        ),
    ]
