# Generated by Django 3.1.7 on 2021-11-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_delete_acceptedcampaign'),
        ('discovery', '0020_auto_20211124_1750'),
        ('dashboard', '0005_auto_20211126_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptedCampaign',
            new_name='AssignedCampaign',
        ),
        migrations.RenameField(
            model_name='assignedcampaign',
            old_name='assigned_campaign',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='assignedcampaign',
            old_name='request_amount',
            new_name='request_budget',
        ),
    ]
