# Generated by Django 3.1.7 on 2021-11-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_delete_acceptedcampaign'),
        ('dashboard', '0006_auto_20211126_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcampaign',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
