# Generated by Django 3.1.7 on 2021-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211126_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcampaign',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedcampaign',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
