# Generated by Django 3.1.7 on 2021-12-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211126_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedCampaign',
        ),
    ]
