# Generated by Django 3.1.7 on 2021-03-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram_data',
            field=models.JSONField(),
        ),
    ]
