# Generated by Django 3.1.7 on 2021-03-01 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210301_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social', to='accounts.userprofile'),
        ),
    ]
