# Generated by Django 3.1.7 on 2021-03-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210301_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
