# Generated by Django 3.1.7 on 2021-03-04 23:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210302_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='instagram_data',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='connected_profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='InstgramData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('social_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to='accounts.socialmedia')),
            ],
        ),
    ]
