# Generated by Django 3.1.7 on 2021-03-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_socialmedia_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstgramData',
            new_name='InstagramData',
        ),
    ]
