# Generated by Django 3.1.7 on 2021-03-07 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20210307_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('subscribers', models.IntegerField(blank=True, null=True)),
                ('videoCount', models.IntegerField(blank=True, null=True)),
                ('viewCount', models.IntegerField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('social_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube', to='accounts.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalYoutubeData',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('subscribers', models.IntegerField(blank=True, null=True)),
                ('videoCount', models.IntegerField(blank=True, null=True)),
                ('viewCount', models.IntegerField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('social_profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.socialmedia')),
            ],
            options={
                'verbose_name': 'historical youtube data',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
