# Generated by Django 3.1.7 on 2021-03-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210308_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalyoutubedata',
            name='avgViews',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubedata',
            name='avgViews',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
