# Generated by Django 3.1.7 on 2021-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210408_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsocialmedia',
            name='jumpnow_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='jumpnow_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
