# Generated by Django 3.1.7 on 2021-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210408_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsocialmedia',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsocialmedia',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalsocialmedia',
            name='featured_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='featured_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
