# Generated by Django 3.1.7 on 2021-05-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210522_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsocialmedia',
            name='contact_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='accounts.contact'),
        ),
    ]
