# Generated by Django 3.1.7 on 2021-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_youtubeauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeauth',
            old_name='access_token',
            new_name='cliend_id',
        ),
        migrations.RemoveField(
            model_name='youtubeauth',
            name='expires',
        ),
        migrations.AddField(
            model_name='youtubeauth',
            name='client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubeauth',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubeauth',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubeauth',
            name='token_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
