# Generated by Django 3.1.7 on 2021-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210610_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered',
            field=models.BooleanField(default=True),
        ),
    ]
