# Generated by Django 3.1.7 on 2021-07-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userprofile_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='followings',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='instagram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='posts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='profile_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='followings',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='instagram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='posts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='creators/instagram/'),
        ),
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('social_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website', to='accounts.socialmedia')),
            ],
        ),
    ]
