# Generated by Django 3.1.7 on 2021-08-27 16:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210714_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramdata',
            options={'ordering': ['-username']},
        ),
        migrations.AlterField(
            model_name='instagramdata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.ig_profile_pic),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketer/'),
        ),
    ]
