# Generated by Django 3.1.7 on 2021-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210913_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('HN', 'Hindi'), ('BN', 'Bengali'), ('UR', 'Urdu'), ('PN', 'Punjabi'), ('MR', 'Marathi'), ('TL', 'Telugu'), ('TM', 'Tamil'), ('GJ', 'Gujarati'), ('KN', 'Kannada'), ('OD', 'Odia'), ('ML', 'Malayalam'), ('AS', 'Assamese'), ('ST', 'Santali'), ('SK', 'Sanskrit')], max_length=100, null=True),
        ),
    ]
