# Generated by Django 3.1.7 on 2021-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_facebookdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltwitterdata',
            name='followers',
            field=models.BigIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='followers',
            field=models.BigIntegerField(blank=True, default=10, null=True),
        ),
    ]
