# Generated by Django 3.1.7 on 2021-10-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210923_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ethnicity',
            new_name='location',
        ),
    ]
