# Generated by Django 3.1.7 on 2021-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_userprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
