# Generated by Django 3.1.7 on 2021-11-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_userprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstagramdata',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
