# Generated by Django 3.1.7 on 2021-11-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20211101_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstagramdata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instagramdata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
