# Generated by Django 3.1.7 on 2021-11-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20211101_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookdata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaltwitterdata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalyoutubedata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='youtubedata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
