# Generated by Django 3.1.7 on 2021-11-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20211031_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='user_profile_image/'),
            preserve_default=False,
        ),
    ]
