# Generated by Django 3.1.7 on 2021-11-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20211101_1657'),
        ('accounts', '0045_auto_20211031_2141'),
    ]

    operations = [
    ]
