# Generated by Django 3.1.7 on 2021-12-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_userprofile_profile_picture'),
        ('accounts', '0046_auto_20211101_1657'),
    ]

    operations = [
    ]
