# Generated by Django 3.1.7 on 2021-11-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20211101_1657'),
        ('accounts', '0046_userprofile_profile_picture'),
    ]

    operations = [
    ]
