# Generated by Django 3.1.7 on 2021-11-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_merge_20211108_1623'),
        ('accounts', '0046_userprofile_profile_picture'),
    ]

    operations = [
    ]
