# Generated by Django 3.1.7 on 2021-11-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_merge_20211109_1057'),
        ('accounts', '0047_merge_20211110_1529'),
    ]

    operations = [
    ]
