# Generated by Django 3.1.7 on 2021-11-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20211126_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptedCampaign',
        ),
    ]
