# Generated by Django 3.1.7 on 2021-12-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_delete_acceptedcampaign'),
        ('accounts', '0048_userprofile_auth_token'),
    ]

    operations = [
    ]
