# Generated by Django 3.1.7 on 2022-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20220126_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_details',
            name='routing_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bank_details',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
