# Generated by Django 3.1.7 on 2022-01-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20220127_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_details',
        ),
    ]
