# Generated by Django 3.1.7 on 2022-01-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_remove_userprofile_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
