# Generated by Django 3.1.7 on 2022-02-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_instagram_temp_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram_temp_data',
            name='user',
        ),
        migrations.AddField(
            model_name='instagram_temp_data',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
