# Generated by Django 3.1.7 on 2021-03-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210308_0117'),
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryprofile',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovery', to='accounts.userprofile'),
        ),
    ]
