# Generated by Django 3.1.7 on 2021-04-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_campaign_campaignlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='lists',
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='discovery.discoveryprofile'),
        ),
        migrations.AddField(
            model_name='campaignlist',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discovery.campaign'),
        ),
    ]
