# Generated by Django 3.1.7 on 2021-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_auto_20210408_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='exports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='searches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
