# Generated by Django 3.1.7 on 2021-05-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_auto_20210520_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='razorpay_sub_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
