# Generated by Django 3.1.7 on 2021-05-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_subscription_razorpay_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
