# Generated by Django 3.1.7 on 2021-05-22 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('discovery_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='discovery.discoveryprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discovery.subscription')),
            ],
        ),
    ]
