# Generated by Django 3.1.7 on 2021-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_subscriptionpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayments',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
