# Generated by Django 3.1.7 on 2021-09-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0011_auto_20210522_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignlist',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discovery.campaignlist'),
        ),
    ]
