# Generated by Django 3.1.7 on 2021-09-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0012_auto_20210920_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign',
            new_name='campaign_list',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='name',
            new_name='list_name',
        ),
    ]
