# Generated by Django 3.1.7 on 2021-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0014_auto_20210920_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_list',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_list',
            field=models.ManyToManyField(blank=True, null=True, to='discovery.campaignList'),
        ),
    ]
