# Generated by Django 3.1.7 on 2021-10-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0015_auto_20210920_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bidding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignlist',
            name='platform',
            field=models.CharField(blank=True, choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=100, null=True),
        ),
    ]
