# Generated by Django 3.1.7 on 2021-11-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0016_auto_20211027_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlist',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_list', to='discovery.discoveryprofile'),
        ),
    ]
