# Generated by Django 3.1.7 on 2021-11-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0017_campaignlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_list', to='discovery.discoveryprofile'),
        ),
    ]
