# Generated by Django 3.1.7 on 2021-11-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0018_auto_20211108_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_deliverables',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='marketer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='marketer_status',
            field=models.BooleanField(default=False),
        ),
    ]
