# Generated by Django 3.1.7 on 2021-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0019_auto_20211124_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='negotiation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='offered_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='settled_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
