# Generated by Django 3.1.7 on 2021-12-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_delete_acceptedcampaign'),
        ('discovery', '0020_auto_20211124_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_creators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_budget', models.IntegerField(blank=True, default=0, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='assigned_creators',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discovery.assigned_creators'),
        ),
    ]
