# Generated by Django 3.1.7 on 2021-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0022_auto_20211201_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='assigned_creators',
        ),
        migrations.AddField(
            model_name='campaign',
            name='assigned_creators',
            field=models.ManyToManyField(blank=True, null=True, to='discovery.AssignedCreators'),
        ),
    ]
