# Generated by Django 3.1.7 on 2021-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0024_auto_20211201_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='assigned_creators',
            field=models.ManyToManyField(blank=True, null=True, to='discovery.AssignedCreators'),
        ),
    ]
