# Generated by Django 3.1.7 on 2021-12-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0026_assignedcreators_amount_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcreators',
            name='offered_amount',
            field=models.BooleanField(default=False),
        ),
    ]
