# Generated by Django 3.1.7 on 2021-12-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0027_assignedcreators_offered_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcreators',
            old_name='amount_requested',
            new_name='requested_amount',
        ),
    ]
