# Generated by Django 3.1.7 on 2021-12-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_delete_acceptedcampaign'),
        ('discovery', '0029_auto_20211204_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivarables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Post', 'Post'), ('Story', 'Story'), ('Video', 'Video')], max_length=100, null=True)),
                ('deliverable', models.CharField(blank=True, choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=100, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
