# Generated by Django 3.1.7 on 2021-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0032_auto_20211211_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivarables',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
