# Generated by Django 3.1.7 on 2021-12-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0033_delivarables_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivarables',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='discovery/screenshot'),
        ),
    ]
