# Generated by Django 3.1.7 on 2021-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0034_delivarables_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivarables',
            name='content_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
