# Generated by Django 3.1.7 on 2021-12-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0035_delivarables_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivarables',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
