# Generated by Django 3.1.7 on 2021-12-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0038_assignedcreators_settled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcreators',
            old_name='delivarables',
            new_name='deliverables',
        ),
    ]
