# Generated by Django 3.1.7 on 2021-12-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_merge_20211215_1304'),
        ('discovery', '0039_auto_20211216_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivarables',
            new_name='Deliverables',
        ),
    ]
