# Generated by Django 3.1.7 on 2021-12-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0040_auto_20211216_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcreators',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignedcreators',
            name='rzrpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignedcreators',
            name='rzrpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
