# Generated by Django 3.1.7 on 2021-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0041_auto_20211216_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverables',
            old_name='status',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='deliverables',
            name='review_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverables',
            name='review_sent',
            field=models.BooleanField(default=False),
        ),
    ]
