# Generated by Django 3.1.7 on 2021-12-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0042_auto_20211219_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables',
            name='remark',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
