# Generated by Django 3.1.7 on 2021-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0043_deliverables_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables',
            name='confirmation_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
